version: "3.8"
services:
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: axoliz
      POSTGRES_PASSWORD: 'axoliz'
      POSTGRES_DB: axoliz_blog
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/your_database

volumes:
  db_data:
